### ISSUE TITLE
Command line multiple interfaces

### ISSUE THREAD

**Issue by DigiAngel** [J-Gras/bro-af_packet-plugin#1]
Topic :)  Currently I'm running bro via command line like so:
~~~
bro -i eth0 -i eth1
~~~

I'd like to use af_packet, but it looks like I can only pass one or the other interface, not both as when I try this:
~~~
bro -i af_packet::eth0 -i af_packet::eth1
~~~
I get:
~~~
fatal error in <params>, line 1: problem with interface af_packet::eth1 (Invalid argument)
~~~
Thank you!

**Comment by J-Gras** [comment]
The main use case of the AF_Packet plugin is to load balance traffic across multiple bro instances. Therefor all instances have to join the same fanout group. A fanout group however cannot span across multiple interfaces. I think that's why the second interface reports an invalid argument in your case: The plugin tries to bring up both interfaces in the same fanout group. In a cluster setup you might use ``af_packet_fanout_id`` in node.cfg to configure distinct fanout groups.

That all said, I am curious: Why do you want to use AF_Packet for a single Bro instance?

**Comment by DigiAngel** [comment]
Ah....well truth be told I'm just experimenting with optimizing how bro functions....very few options are command line...mostly only in clusters with workers and what not.  I'll close this out...thank you.

**Comment by J-Gras** [comment]
I am happy I could shed some light on this. In case you don't need fanout for multiple workers you might try to set ``enable_fanout = F``. If you want to explore cluster setups the following might be a good start: https://www.bro.org/sphinx-git/configuration/index.html (just use AF_Packet instead of PF_RING ;)
