### ISSUE TITLE
Copy VLAN info in

### ISSUE THREAD

**Issue by dcode** [J-Gras/bro-af_packet-plugin#9]
Recent versions of Suricata are able to pull in VLAN information from AF_Packet, though I think only one layer deep (i.e. no Q-in-Q). The source driver is [here](https://github.com/OISF/suricata/blob/master/src/source-af-packet.c#L944). Is this feasible in the Bro plugin?

**Comment by J-Gras** [comment]
Unfortunately not. The kernel strips off the VLAN tag and stores the information in the meta data structure it provides for each packet (`tpacket2_hdr`). Suricata reads the VLAN information from there and passes it to the right places. In Suricata this isn't a great deal because of its monolithic structure. In Zeek/Bro Packet Sources are designed to provide just the packets and there is no way to pass additional meta data. From an architectural point of view this makes sense as the VLAN tags should be part of the packets and should be parsed by Zeek/Bro. The ugly workaround would be to put the VLAN tags back in the packet.
